# Generated by Django 3.0.3 on 2020-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200503_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like_nums',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
